events {
    worker_connections 1024;
}

http {
    upstream hotel {
        server hotel-service:8001;
    }
    upstream restaurant {
        server restaurant-service:8002;
    }
    upstream realestate {
        server realestate-service:8003;
    }
    upstream analytics {
        server analytics-service:8004;
    }
    upstream chatbot {
        server chatbot-service:8005;
    }

    server {
        listen 80;
        server_name _;

        # Health
        location /health {
            return 200 '{"status":"ok","service":"gateway"}' ;
            add_header Content-Type application/json;
        }

        location /hotel/ {
            proxy_pass http://hotel/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /restaurant/ {
            proxy_pass http://restaurant/;
            proxy_set_header Host $host;
        }
        location /realestate/ {
            proxy_pass http://realestate/;
            proxy_set_header Host $host;
        }
        location /analytics/ {
            proxy_pass http://analytics/;
            proxy_set_header Host $host;
        }
        location /chatbot/ {
            proxy_pass http://chatbot/;
            proxy_set_header Host $host;
        }
    }
}
